---
title: "analysis_1"
author: "Haodong Li"
date: "2023-02-03"
output: pdf_document
---


```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(kableExtra)
library(readr)
library(dplyr)
library(sl3)
library(tictoc)
library(tmle3)
library(ggplot2)
library(table1)
library(ggpubr)
library(R6)

rm(list = ls())
repo_path = "~/Repo/te_vim/"
source(paste0(repo_path, "R/data_process/data_helper.R"))
source(paste0(repo_path, "R/simu/simu_dgd.R")) 
source(paste0(repo_path, "R/simu/simu_config.R"))
source(paste0(repo_path, "R/est_function/sl3_config.R"))
source(paste0(repo_path, "R/est_function/fit_para.R"))
source(paste0(repo_path, "R/est_function/vim.R"))
source(paste0(repo_path, "R/analysis/analy_helper.R"))
source(paste0(repo_path, "R/est_function/fit_paraloop.R"))
df_w <- read_csv(file = paste0(repo_path, "data/supp/df_w.csv"))
# df_fit <- readRDS("~/Repo/te_vim/data/df_fit.RDS")
cm_names <- c("statin_use", "antihypertensives", "betab", "minera", "adp",
              "vkantag", "caantag", "thiazide", "loopdiur")
```

## 1. Stratified TMLE
```{r}
df_strat <- readRDS("~/Repo/te_vim/data/df_strat.RDS")
p_cate_strat <- plot_tmle_strat(cm_names, df_strat)
p_cate_strat
```


## 2. TMLE Effect Modification
```{r}
df_em <- readRDS("~/Repo/te_vim/data/df_em.RDS")
p_cate_strat <- plot_tmle_em(cm_names, df_em)
p_cate_strat
```


## 3. VTE Estimation
```{r}
res_vte <-  readRDS("~/Repo/te_vim/data/res_vte_t.RDS")

print(paste0("VTE TMLE:"))
print(paste0("coef:", res_vte$res_tmle$coef))
print(paste0("ci low:", res_vte$res_tmle$ci_l))
print(paste0("ci up:", res_vte$res_tmle$ci_u))


print(paste0("VTE EE:"))
print(paste0("coef:", res_vte$res_ee$coef))
print(paste0("ci low:", res_vte$res_ee$ci_l))
print(paste0("ci up:", res_vte$res_ee$ci_u))
```


## 4. VIM Estimation
```{r, echo=FALSE, fig.cap="VIM estiamtes", out.width = '150%', fig.align="center", fig.pos="H"}
df_theta <-  readRDS("~/Repo/te_vim/data/df_vim_t.RDS")

p_theta_ee <- plot_theta(df_theta, estimator = "EE")
p_theta_tmle <- plot_theta(df_theta, estimator = "TMLE")
p_theta_ss <- plot_theta(df_theta, estimator = "SS")

p_theta_all <-
  ggarrange(p_theta_ee + ggtitle("EE VIM estimates (T-learner)"),
            p_theta_tmle + ggtitle("TMLE VIM estimates (T-learner)"),
            p_theta_ss + ggtitle("SS VIM estimates (T-learner)"))

p_theta_all
```














