---
title: "Untitled"
author: "Haodong Li"
date: "2022-10-03"
output:
  pdf_document:
    keep_tex: true
---

```{r, echo=FALSE}
library(formattable)
library(tables)
library(stargazer)
library(kableExtra)
library(tidyr)
library(dplyr)
library(data.table)
library(readr)
```

```{r}
output_filename <- paste0('~/Repo/te_vim/simu_res/theta_s/',"local_", 500, "_", '2022-10-02','.csv')
res1 <- read_csv(output_filename) %>% mutate(n = 500)

output_filename <- paste0('~/Repo/te_vim/simu_res/theta_s/',"local_", 2000, "_", '2022-10-02','.csv')
res2 <- read_csv(output_filename) %>% mutate(n = 2000)

output_filename <- paste0('~/Repo/te_vim/simu_res/theta_s/',"local_", 5000, "_", '2022-10-02','.csv')
res3 <- read_csv(output_filename) %>% mutate(n = 5000)

output_filename <- paste0('~/Repo/te_vim/simu_res/theta_s/',"local_", 7000, "_", '2022-10-03','.csv')
res4 <- read_csv(output_filename) %>% mutate(n = 7000)

output_filename <- paste0('~/Repo/te_vim/simu_res/theta_s/',"local_", 10000, "_", '2022-10-03','.csv')
res5 <- read_csv(output_filename) %>% mutate(n = 10000)

res <- rbind(res1, res2, res3, res4, res5)
```

```{r}
output_filename <- paste0('~/Repo/te_vim/simu_res/theta_s/',"local_correct_", 500, "_", '2022-10-04','.csv')
res1 <- read_csv(output_filename) %>% mutate(n = 500)

output_filename <- paste0('~/Repo/te_vim/simu_res/theta_s/',"local_correct_", 1000, "_", '2022-10-04','.csv')
res2 <- read_csv(output_filename) %>% mutate(n = 1000)

res <- rbind(res1, res2)
```

```{r, echo=FALSE}
res$truth <- 0.685757
table_results_data <- res %>%
  dplyr::mutate(cvtmle_proportion = truth <= cvtmle_upper & truth >= cvtmle_lower,
                cvaiptw_proportion = truth <= cvaiptw_upper & truth >= cvaiptw_lower,
                
                cvtmle_widthCI = cvtmle_upper-cvtmle_lower,
                cvaiptw_widthCI = cvaiptw_upper-cvaiptw_lower,
  ) %>%
  dplyr::group_by(n, truth) %>%
  summarize(cvtmle_coverage = mean(cvtmle_proportion),
            cvaiptw_coverage = mean(cvaiptw_proportion),
            
            cvtmle_bias = mean(cvtmle) - mean(truth),
            cvaiptw_bias = mean(cvaiptw) - mean(truth),

            cvtmle_var = var(cvtmle),
            cvaiptw_var = var(cvaiptw),

            cvtmle_mse = cvtmle_bias^2 + var(cvtmle),
            cvaiptw_mse = cvaiptw_bias^2 + var(cvaiptw),
            
            
            # 2020-02-01 coverage of oracle CI
            cvtmle_oracle = mean(truth <= cvtmle + 1.96*sd(cvtmle) & truth >= cvtmle - 1.96*sd(cvtmle)),
            cvaiptw_oracle = mean(truth <= cvaiptw + 1.96*sd(cvaiptw) & truth >= cvaiptw - 1.96*sd(cvaiptw)),

            cvtmle_meanwidthCI = mean(cvtmle_widthCI),
            cvaiptw_meanwidthCI = mean(cvaiptw_widthCI)

  ) %>%  ungroup()
```

#wide to long
```{r, echo=FALSE}
data_long_coverage <- gather(table_results_data, method, coverage, cvtmle_coverage:cvaiptw_coverage, factor_key=TRUE) %>%select(c(n, truth, method, coverage))

data_long_oracle <- gather(table_results_data, method, oracle_coverage, cvtmle_oracle:cvaiptw_oracle, factor_key=TRUE) %>% select(c(oracle_coverage))

data_long_bias <- gather(table_results_data, method, bias, cvtmle_bias:cvaiptw_bias, factor_key=TRUE) %>% select(c(bias))

data_long_var<- gather(table_results_data, method, var, cvtmle_var:cvaiptw_var, factor_key=TRUE) %>%select(c(var))

data_long_mse <- gather(table_results_data, method, mse, cvtmle_mse:cvaiptw_mse, factor_key=TRUE) %>%select(c(mse))

data_long_CIwidth <- gather(table_results_data, method, CIwidth, cvtmle_meanwidthCI:cvaiptw_meanwidthCI, factor_key=TRUE) %>%select(c(CIwidth))
```
#merge
```{r, echo=FALSE}
data_long = cbind(data_long_coverage,
                  data_long_oracle, 
                  data_long_bias,
                  data_long_var,
                  data_long_mse,
                  data_long_CIwidth) %>% 
  select(c(n, method,truth,var,bias,mse,coverage,oracle_coverage, CIwidth))

setnames(data_long, old = c('n' ,'method','truth','var','bias','mse','coverage','oracle_coverage','CIwidth'), 
         new = c ('n',"Method",'True_Theta','Variance','Bias','MSE','Coverage','Coverage_or','CI_width'))

data_long$Method = c(rep('CV-TMLE',2), rep('CV-EE',2))
data_long <- data_long %>% arrange(n)
```



\newpage
```{r}
data_long %>% 
  mutate(across(where(is.numeric), ~ round(., 3))) %>% 
  kable("latex", booktabs = T, caption = "Performance of CV-TMLE and CV-EE for Theta") %>% 
  collapse_rows(columns = 1, latex_hline = "major", valign = "middle")%>%
  kable_styling(latex_options = "scale_down")
```
